team-heisenberg/stylify

api/prisma/schema.prisma

Pushing the data model implemented in Prisma for Appointment, AppointmentDetails and Customer Table.
```
npm run
```
1. 
2.
---

feature: appointment/appointmentDetails/customer Tables

---

api/prisma/migrations/20230210030309_initial_schema/migration.sql
api/prisma/schema.prisma

Migrations Setup

---

api/src/routes/appointmentRouter.ts
api/src/routes/businessRouter.ts
api/src/routes/professionalRouter.ts

- Appointment
- Business
- Professional

Professional, Business and Appointment routes

---

api/src/routes/appointmentDetailsRouter.ts
api/src/routes/customerRouter.ts
api/src/routes/reviewRouter.ts

routes for appointmentDetails, customer and review
```
npm run
```
1. 
2.
---

feature: routes appointmentDetails, customer and review

---

api/src/routes/professionalServicesRouter.ts
api/src/routes/serviceRouter.ts
api/tsconfig.json

> professionalServicesRouter and serviceRouter
```
npm run
```
1. 
2.
---

feature-professionalServicesRouter-and-serviceRouter

---

app/App.tsx
app/src/screens/StoryBoard/StoryBoard.tsx

feature: StoryBoard Page

---

api/package.json

Fixed build script

---

app/src/components/ImageComponent/ImageComponent.tsx
app/src/screens/StoryBoard/StoryBoard.tsx

feature: image component

---

app/src/components/Radio/Radio.tsx
app/src/screens/StoryBoard/StoryBoard.tsx

> Radio component in progress
need to find a way to add values to each radio and add a label text from text component
```
npm run
```
1. 
2.
---

radio component work in progress

---

api/package-lock.json
api/package.json
api/seeds/seed.ts
api/src/routes/appointmentDetailsRouter.ts
api/src/routes/appointmentRouter.ts
api/src/routes/businessRouter.ts
api/src/routes/customerRouter.ts
api/src/routes/dealRouter.ts
api/src/routes/index.ts
api/src/routes/professionalRouter.ts
api/src/routes/professionalServicesRouter.ts
api/src/routes/reviewRouter.ts
api/src/routes/serviceRouter.ts
api/src/routes/serviceTypeRouter.ts
app/src/screens/StoryBoard/StoryBoard.tsx

> route files updated
```
npm run
```
1. 
2.
---

bug: route files updated

---

app/src/components/InputCheck/InputCheck.tsx
app/src/components/NormalText/NormalText.tsx
app/src/screens/StoryBoard/StoryBoard.tsx

feature: final version check button

---

app/App.tsx
app/package-lock.json
app/package.json
app/src/components/ImageComponent/ImageComponent.tsx
app/src/components/NormalText/NormalText.tsx
app/src/screens/StoryBoard/StoryBoard.tsx
app/yarn.lock

feature: drop shadow on image component

---

api/src/routes/index.ts
api/src/routes/searchBusinessOrService.ts

Search route

---

app/src/screens/LoginScreen/LoginScreen.tsx

HB-143: Auth integration and routes

---

app/src/screens/HomeCustomer/HomeCustomer.tsx
app/src/stacks/TabNavigatorClient.tsx

Merge issues fixed

---

api/prisma/migrations/20230321073237_appointment_type/migration.sql
api/prisma/migrations/20230321074143_service_price/migration.sql
api/prisma/schema.prisma
api/seeds/seed.ts
api/seeds/utils.ts
api/src/routes/insights.ts

Create an endpoint to get data about appointments by type
**Run command: (inside API folder w/ Docker DB running)**
```
npm run prisma:reset
```
```
npm run prisma:migrate
```
```
npm run prisma:seed
```
How to use the endpoint:
http://localhost:8080/insights/bytype/?initialDate=2023-01-11&finalDate=2023-01-12&businessID=1

[HB-151] DB/ Insights updates

---

app/src/screens/LoginScreen/LoginScreen.tsx
app/src/screens/LoginScreen/SignUpBusiness.tsx
app/src/screens/LoginScreen/SignUpCustomer.tsx

Store data about user creation on firebase to synchronize with the backend data in case of 401, 404, 400 and 500.
**NOTE**: This will only work with new users

[HB-152] Added user Sync

---

api/src/routes/businessRouter.ts
api/src/routes/customerRouter.ts

HB-215: User creation exception handling fixed

---

app/App.tsx
app/package.json
app/src/components/CardAppointment/CardAppointment.tsx
app/src/components/CardRecentAppointment/CardRecentAppointment.tsx
app/src/components/CardSalon/CardSalon.tsx
app/src/components/FavButton/FavButton.tsx
app/src/components/InputComponent/InputComponent.tsx
app/src/components/NormalText/FontTypes.ts
app/src/screens/BusinessProfile/BusinessProfile.tsx
app/src/screens/HomeBusiness/HomeBusiness.tsx
app/src/screens/HomeCustomer/HomeCustomer.tsx
app/yarn.lock

Added the following fonts
- Playfair Display
- Figtree
```
yarn
```
1. Open the app
2. Check the fonts against [Mockups](https://www.figma.com/file/8Tz3dBEdaO3TxQUFsiFEvS/Stylify?node-id=1515-34040&t=qkxrsLgNL1LoLy0l-0)
---

HB-146: Fonts and minor style fixes added

---

api/src/routes/appointmentRouter.ts
app/src/screens/HomeBusiness/ConfirmAppointmentBusiness.tsx
app/src/screens/HomeBusiness/SelectProfessionalBusiness.tsx

Dates fixed

---

app/package.json
app/src/components/StarComponent/StarComponent.tsx
app/src/components/TabViewComponent/TabViewComponent.tsx
app/src/containers/PieChartContainer/PieChartContainer.tsx
app/src/screens/InsightsBusiness/AppointmentsInsights.tsx
app/src/screens/InsightsBusiness/GeneralInsights.tsx
app/src/screens/InsightsBusiness/InsightsBusiness.tsx
app/src/screens/InsightsBusiness/Reviews.tsx
app/src/screens/MoreBusiness/MoreBusiness.tsx
app/yarn.lock

fix insights when there is not data, 
added real business info on Business more screen, 
fixed the height of the app screen
```
npm run
```

fix insights, added real business info on Business more, fixed the height of the app

---

app/src/components/NormalText/FontTypes.ts
app/src/screens/Browse/Browse.tsx
app/src/screens/Deals/Deals.tsx
app/src/screens/Profile/Profile.tsx

feature: visual improvements

---

api/prisma/migrations/20230415024105_appointment_data_and_time/migration.sql
api/prisma/schema.prisma
api/src/routes/appointmentRouter.ts
app/src/screens/HomeBusiness/ConfirmAppointmentBusiness.tsx
app/src/screens/HomeBusiness/HomeBusiness.tsx
app/src/screens/HomeBusiness/SelectProfessionalBusiness.tsx
app/src/utils/index.ts

Before using the new routes run:
**Run command inside `api` folder:**
```
npm run prisma:migrate
```
**New Endpoints**
| endpoint | Header |
|--------|--------|
| /appointment/upcomingByBusiness/:businessID | Get Upcoming Appointment  by Business |
| /appointment/upcomingByCustomer/:customerID | Get Upcoming Appointment  by Customer | 
To render the appointment date and time use the property `dateAndTime` from the appointment object. Also, use the function `removeYear` located at `app/src/utils/index.ts`
---

Date and time fixed, upcoming

---

api/src/routes/appointmentRouter.ts
app/src/screens/HomeBusiness/HomeBusiness.tsx
app/src/screens/HomeBusiness/SelectServicesBusiness.tsx

> Homepage displaying right information
```
npm run
```
1. 
2.
---

Hb 232 style business home page

---

api/src/routes/appointmentRouter.ts
app/src/components/CardAppointment/CardAppointment.tsx
app/src/screens/HomeBusiness/HomeBusiness.tsx
app/src/screens/HomeCustomer/HomeCustomer.tsx

> Customer-Side-Change-Appointment-Card-Endpoint
```
npm run
```
1. 
2.
---

Customer-Side-Change-Appointment-Card-Endpoint

---

api/package.json
api/prisma/migrations/20230416001022_services_photos/migration.sql
api/prisma/migrations/20230416001145_services_photos_2/migration.sql
api/prisma/schema.prisma
api/seeds/seed-prod.ts
api/seeds/utils.ts
api/src/routes/appointmentRouter.ts
app/src/components/CardService/CardService.tsx
app/src/containers/BookingServiceContainer/BookingServiceContainer.tsx
app/src/screens/Booking/About.tsx
app/src/screens/Booking/Booking.tsx
app/src/screens/Booking/BookingServices.tsx
app/src/screens/Booking/BookingSpecialists.tsx
app/src/screens/HomeBusiness/SelectServicesBusiness.tsx
app/src/screens/HomeCustomer/HomeCustomer.tsx
app/src/screens/InsightsBusiness/GeneralInsights.tsx
app/src/screens/InsightsBusiness/Reviews.tsx
app/src/screens/MoreBusiness/MoreBusiness.tsx

Database changes and UI updates related to the data;
**Run command inside API folder**
```
npm run prisma:migrate
```

HB-238-Real-Data-Creation

---

api/src/app.ts
api/src/routes/appointmentRouter.ts
app/src/components/Message/Message.tsx
app/src/screens/HomeBusiness/ConfirmAppointmentBusiness.tsx
app/src/screens/HomeBusiness/HomeBusiness.tsx
app/src/screens/HomeCustomer/HomeCustomer.tsx

> Hb 237 refresh data after post appointments
```
npm run
```
1. 
2.
---

Hb 237 refresh data after post appointments

---

app/src/components/Card/Card.tsx
app/src/components/CardAppointment/CardAppointment.tsx
app/src/components/CardRecentAppointment/CardRecentAppointment.tsx
app/src/components/CardSalon/CardSalon.tsx
app/src/components/CardService/CardService.tsx
app/src/components/NormalText/FontTypes.ts
app/src/components/SearchComponent/SearchResultListItem.tsx
app/src/components/StarComponent/StarComponent.tsx
app/src/containers/BookingServiceContainer/BookingServiceContainer.tsx
app/src/screens/Booking/Booking.tsx
app/src/screens/Booking/BookingServices.tsx
app/src/screens/Browse/Browse.tsx
app/src/screens/Deals/Deals.tsx
app/src/screens/HomeBusiness/AppointmentDetails.tsx
app/src/screens/HomeBusiness/HomeBusiness.tsx
app/src/screens/HomeBusiness/SelectProfessionalBusiness.tsx
app/src/screens/HomeBusiness/SelectServicesBusiness.tsx
app/src/screens/HomeCustomer/HomeCustomer.tsx
app/src/screens/MoreBusiness/MoreBusiness.tsx
app/src/stacks/StackNav.tsx

created appointment details screen, and fixed styling overall

---

app/src/screens/HomeBusiness/ConfirmAppointmentBusiness.tsx
app/src/screens/HomeCustomer/HomeCustomer.tsx

> cleaning code
```
npm run
```
1. 
2.
---

cleaning code
